### ISSUE TITLE
Can it be related to the particular VEQ version?

### ISSUE THREAD

**Issue by psychedel** [inconvergent/weird#3]
First of all - thank you for such an interesting project!
I have an error with this example - https://github.com/inconvergent/weird/blob/master/examples/draw.lisp

```
READ error during COMPILE-FILE:
;   
;     Symbol "F3$S" not found in the VEQ package.
;   
;       Line: 161, Column: 46, File-Position: 5793
;   
;       Stream: #<SB-INT:FORM-TRACKING-STREAM for "file ...\\quicklisp\\local-projects\\weird\\src\\draw\\ortho.lisp" {100533FB33}>
```

**Comment by inconvergent** [comment]
i'm afraid the HEAD of weird in this repo is out of sync with the veq version in quicklisp. 

it should work if you clone veq locally and tell quicklisp to use the cloned repo.

there are instructions on how to do this in the ql docs, but the short of it is that you need a symlink to veq in `~/quicklisp/local-projects/`. 

ql docs: https://www.quicklisp.org/beta/faq.html
veq: https://github.com/inconvergent/cl-veq

**Comment by inconvergent** [comment]
as a side note. i am working on updated versions of both veq and weird. and when i publish the updated code i will try to ensure things are in sync. but i have not been able to finish it yet.

**Comment by psychedel** [comment]
Thank you - I've tried but with no luck yet. Probably new "veq" was in system somewhere already.
I will read more about the quicklisp uninstall and local packages.

Thanks!

**Comment by inconvergent** [comment]
yeah, im afraid you will have to fiddle around with it. but it should be possible to override which veq is loaded by quicklisp. that's how i do it locally. i followed the ql instructions in the link above
